# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{gameday_api}
  s.version = "0.5.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["timothyf"]
  s.date = %q{2010-07-18}
  s.description = %q{An API for processing live MLB statistics.}
  s.email = %q{timothyf@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README"
  ]
  s.homepage = %q{http://github.com/timothyf/gameday_api}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.files = Dir['lib/**/*.rb'] + Dir['lib/**/*.yml']
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{An API for processing live MLB statistics.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
